site_name: Passing the Torch
theme:
  name: material
  palette:
    # primary: success.main
    # accent: white
  font:
    text: Ubuntu
  icon:
    logo: material/torch
  favicon: images/torch.png
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  # - pymdownx.emoji:
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
extra_css:
  - stylesheets/extra.css
nav:
  - index.md
  - pytorch_vs_numpy.md
  - autograd.md
  - neural_networks.md
  - training.md
  - embeddings.md

  
